template: testify
formatter: goimports
log-level: "error"
packages:
  github.com/eshadow1/shortener/internal:
    config:
      all: true
      recursive: true
      dir: "mocks/{{.SrcPackageName}}"
      filename: "mock_{{.InterfaceName}}.go"
      inpackage: false