-- +migrate Up

CREATE TABLE IF NOT EXISTS shorten (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    shorten_url VARCHAR(255) NOT NULL,
    original_url VARCHAR(1024) NOT NULL UNIQUE
    );