package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/eshadow1/shortener/reset"
)

const (
	permFile = 0600
)

func main() {
	pkgMethods := make(map[string][]string)
	pkgNames := make(map[string]string)

	wd, _ := os.Getwd()
	utilityDir := filepath.Join(wd, "cmd", "reset")

	err := filepath.WalkDir(".", func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		absPath, _ := filepath.Abs(path)
		if strings.HasPrefix(absPath, utilityDir) {
			return nil
		}

		if d.IsDir() || !strings.HasSuffix(path, ".go") {
			return nil
		}

		if strings.HasSuffix(path, "_test.go") || strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		structs, pkgName, err := reset.ProcessFile(path)
		if err != nil {
			return nil
		}

		dir := filepath.Dir(path)
		pkgNames[dir] = pkgName

		for _, s := range structs {
			method := reset.GenerateResetMethod(s.TypeName, s.Receiver, s.Fields)
			pkgMethods[dir] = append(pkgMethods[dir], method)
		}

		return nil
	})

	if err != nil {
		fmt.Fprintf(os.Stderr, "Ошибка обхода директорий: %v\n", err)
		os.Exit(1)
	}

	for dir, methods := range pkgMethods {
		if len(methods) == 0 {
			continue
		}

		pkgName := pkgNames[dir]
		var buf bytes.Buffer
		buf.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n\n")
		fmt.Fprintf(&buf, "package %s\n\n", pkgName)

		for _, m := range methods {
			buf.WriteString(m)
			buf.WriteString("\n")
		}

		outPath := filepath.Join(dir, "reset.gen.go")

		errWrite := os.WriteFile(outPath, buf.Bytes(), permFile)
		if errWrite != nil {
			fmt.Fprintf(os.Stderr, "Ошибка записи файла %s: %v\n", outPath, errWrite)
		} else {
			fmt.Printf("Сгенерирован: %s\n", outPath)
		}
	}
}
