// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"github.com/eshadow1/shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuditBroker creates a new instance of MockAuditBroker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditBroker {
	mock := &MockAuditBroker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditBroker is an autogenerated mock type for the AuditBroker type
type MockAuditBroker struct {
	mock.Mock
}

type MockAuditBroker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditBroker) EXPECT() *MockAuditBroker_Expecter {
	return &MockAuditBroker_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function for the type MockAuditBroker
func (_mock *MockAuditBroker) Notify(event model.Event) {
	_mock.Called(event)
	return
}

// MockAuditBroker_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockAuditBroker_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - event model.Event
func (_e *MockAuditBroker_Expecter) Notify(event interface{}) *MockAuditBroker_Notify_Call {
	return &MockAuditBroker_Notify_Call{Call: _e.mock.On("Notify", event)}
}

func (_c *MockAuditBroker_Notify_Call) Run(run func(event model.Event)) *MockAuditBroker_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Event
		if args[0] != nil {
			arg0 = args[0].(model.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuditBroker_Notify_Call) Return() *MockAuditBroker_Notify_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuditBroker_Notify_Call) RunAndReturn(run func(event model.Event)) *MockAuditBroker_Notify_Call {
	_c.Run(run)
	return _c
}
