// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockChecker creates a new instance of MockChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChecker {
	mock := &MockChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChecker is an autogenerated mock type for the Checker type
type MockChecker struct {
	mock.Mock
}

type MockChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChecker) EXPECT() *MockChecker_Expecter {
	return &MockChecker_Expecter{mock: &_m.Mock}
}

// ConnectDB provides a mock function for the type MockChecker
func (_mock *MockChecker) ConnectDB(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ConnectDB")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChecker_ConnectDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectDB'
type MockChecker_ConnectDB_Call struct {
	*mock.Call
}

// ConnectDB is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChecker_Expecter) ConnectDB(ctx interface{}) *MockChecker_ConnectDB_Call {
	return &MockChecker_ConnectDB_Call{Call: _e.mock.On("ConnectDB", ctx)}
}

func (_c *MockChecker_ConnectDB_Call) Run(run func(ctx context.Context)) *MockChecker_ConnectDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChecker_ConnectDB_Call) Return(err error) *MockChecker_ConnectDB_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChecker_ConnectDB_Call) RunAndReturn(run func(ctx context.Context) error) *MockChecker_ConnectDB_Call {
	_c.Call.Return(run)
	return _c
}
