// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/eshadow1/shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateShortURL provides a mock function for the type MockService
func (_mock *MockService) CreateShortURL(context1 context.Context, originalInfos []model.OriginalInfo) ([]model.ShortenInfo, error) {
	ret := _mock.Called(context1, originalInfos)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURL")
	}

	var r0 []model.ShortenInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.OriginalInfo) ([]model.ShortenInfo, error)); ok {
		return returnFunc(context1, originalInfos)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.OriginalInfo) []model.ShortenInfo); ok {
		r0 = returnFunc(context1, originalInfos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShortenInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []model.OriginalInfo) error); ok {
		r1 = returnFunc(context1, originalInfos)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateShortURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortURL'
type MockService_CreateShortURL_Call struct {
	*mock.Call
}

// CreateShortURL is a helper method to define mock.On call
//   - context1 context.Context
//   - originalInfos []model.OriginalInfo
func (_e *MockService_Expecter) CreateShortURL(context1 interface{}, originalInfos interface{}) *MockService_CreateShortURL_Call {
	return &MockService_CreateShortURL_Call{Call: _e.mock.On("CreateShortURL", context1, originalInfos)}
}

func (_c *MockService_CreateShortURL_Call) Run(run func(context1 context.Context, originalInfos []model.OriginalInfo)) *MockService_CreateShortURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.OriginalInfo
		if args[1] != nil {
			arg1 = args[1].([]model.OriginalInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateShortURL_Call) Return(shortenInfos []model.ShortenInfo, err error) *MockService_CreateShortURL_Call {
	_c.Call.Return(shortenInfos, err)
	return _c
}

func (_c *MockService_CreateShortURL_Call) RunAndReturn(run func(context1 context.Context, originalInfos []model.OriginalInfo) ([]model.ShortenInfo, error)) *MockService_CreateShortURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetOriginalURL provides a mock function for the type MockService
func (_mock *MockService) GetOriginalURL(context1 context.Context, shortenInfo model.ShortenInfo) (model.OriginalInfo, error) {
	ret := _mock.Called(context1, shortenInfo)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalURL")
	}

	var r0 model.OriginalInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ShortenInfo) (model.OriginalInfo, error)); ok {
		return returnFunc(context1, shortenInfo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ShortenInfo) model.OriginalInfo); ok {
		r0 = returnFunc(context1, shortenInfo)
	} else {
		r0 = ret.Get(0).(model.OriginalInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.ShortenInfo) error); ok {
		r1 = returnFunc(context1, shortenInfo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetOriginalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOriginalURL'
type MockService_GetOriginalURL_Call struct {
	*mock.Call
}

// GetOriginalURL is a helper method to define mock.On call
//   - context1 context.Context
//   - shortenInfo model.ShortenInfo
func (_e *MockService_Expecter) GetOriginalURL(context1 interface{}, shortenInfo interface{}) *MockService_GetOriginalURL_Call {
	return &MockService_GetOriginalURL_Call{Call: _e.mock.On("GetOriginalURL", context1, shortenInfo)}
}

func (_c *MockService_GetOriginalURL_Call) Run(run func(context1 context.Context, shortenInfo model.ShortenInfo)) *MockService_GetOriginalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ShortenInfo
		if args[1] != nil {
			arg1 = args[1].(model.ShortenInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetOriginalURL_Call) Return(originalInfo model.OriginalInfo, err error) *MockService_GetOriginalURL_Call {
	_c.Call.Return(originalInfo, err)
	return _c
}

func (_c *MockService_GetOriginalURL_Call) RunAndReturn(run func(context1 context.Context, shortenInfo model.ShortenInfo) (model.OriginalInfo, error)) *MockService_GetOriginalURL_Call {
	_c.Call.Return(run)
	return _c
}
