// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRouterHandler creates a new instance of MockRouterHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRouterHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRouterHandler {
	mock := &MockRouterHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRouterHandler is an autogenerated mock type for the RouterHandler type
type MockRouterHandler struct {
	mock.Mock
}

type MockRouterHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRouterHandler) EXPECT() *MockRouterHandler_Expecter {
	return &MockRouterHandler_Expecter{mock: &_m.Mock}
}

// GetCheckDB provides a mock function for the type MockRouterHandler
func (_mock *MockRouterHandler) GetCheckDB(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockRouterHandler_GetCheckDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCheckDB'
type MockRouterHandler_GetCheckDB_Call struct {
	*mock.Call
}

// GetCheckDB is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockRouterHandler_Expecter) GetCheckDB(w interface{}, r interface{}) *MockRouterHandler_GetCheckDB_Call {
	return &MockRouterHandler_GetCheckDB_Call{Call: _e.mock.On("GetCheckDB", w, r)}
}

func (_c *MockRouterHandler_GetCheckDB_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockRouterHandler_GetCheckDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRouterHandler_GetCheckDB_Call) Return() *MockRouterHandler_GetCheckDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouterHandler_GetCheckDB_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockRouterHandler_GetCheckDB_Call {
	_c.Run(run)
	return _c
}

// GetOrigin provides a mock function for the type MockRouterHandler
func (_mock *MockRouterHandler) GetOrigin(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockRouterHandler_GetOrigin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrigin'
type MockRouterHandler_GetOrigin_Call struct {
	*mock.Call
}

// GetOrigin is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockRouterHandler_Expecter) GetOrigin(w interface{}, r interface{}) *MockRouterHandler_GetOrigin_Call {
	return &MockRouterHandler_GetOrigin_Call{Call: _e.mock.On("GetOrigin", w, r)}
}

func (_c *MockRouterHandler_GetOrigin_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockRouterHandler_GetOrigin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRouterHandler_GetOrigin_Call) Return() *MockRouterHandler_GetOrigin_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouterHandler_GetOrigin_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockRouterHandler_GetOrigin_Call {
	_c.Run(run)
	return _c
}

// GetUserURLs provides a mock function for the type MockRouterHandler
func (_mock *MockRouterHandler) GetUserURLs(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockRouterHandler_GetUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserURLs'
type MockRouterHandler_GetUserURLs_Call struct {
	*mock.Call
}

// GetUserURLs is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockRouterHandler_Expecter) GetUserURLs(w interface{}, r interface{}) *MockRouterHandler_GetUserURLs_Call {
	return &MockRouterHandler_GetUserURLs_Call{Call: _e.mock.On("GetUserURLs", w, r)}
}

func (_c *MockRouterHandler_GetUserURLs_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockRouterHandler_GetUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRouterHandler_GetUserURLs_Call) Return() *MockRouterHandler_GetUserURLs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouterHandler_GetUserURLs_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockRouterHandler_GetUserURLs_Call {
	_c.Run(run)
	return _c
}

// PostCreate provides a mock function for the type MockRouterHandler
func (_mock *MockRouterHandler) PostCreate(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockRouterHandler_PostCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostCreate'
type MockRouterHandler_PostCreate_Call struct {
	*mock.Call
}

// PostCreate is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockRouterHandler_Expecter) PostCreate(w interface{}, r interface{}) *MockRouterHandler_PostCreate_Call {
	return &MockRouterHandler_PostCreate_Call{Call: _e.mock.On("PostCreate", w, r)}
}

func (_c *MockRouterHandler_PostCreate_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockRouterHandler_PostCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRouterHandler_PostCreate_Call) Return() *MockRouterHandler_PostCreate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouterHandler_PostCreate_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockRouterHandler_PostCreate_Call {
	_c.Run(run)
	return _c
}

// PostShorten provides a mock function for the type MockRouterHandler
func (_mock *MockRouterHandler) PostShorten(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockRouterHandler_PostShorten_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostShorten'
type MockRouterHandler_PostShorten_Call struct {
	*mock.Call
}

// PostShorten is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockRouterHandler_Expecter) PostShorten(w interface{}, r interface{}) *MockRouterHandler_PostShorten_Call {
	return &MockRouterHandler_PostShorten_Call{Call: _e.mock.On("PostShorten", w, r)}
}

func (_c *MockRouterHandler_PostShorten_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockRouterHandler_PostShorten_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRouterHandler_PostShorten_Call) Return() *MockRouterHandler_PostShorten_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouterHandler_PostShorten_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockRouterHandler_PostShorten_Call {
	_c.Run(run)
	return _c
}

// PostShortenBatch provides a mock function for the type MockRouterHandler
func (_mock *MockRouterHandler) PostShortenBatch(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockRouterHandler_PostShortenBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostShortenBatch'
type MockRouterHandler_PostShortenBatch_Call struct {
	*mock.Call
}

// PostShortenBatch is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockRouterHandler_Expecter) PostShortenBatch(w interface{}, r interface{}) *MockRouterHandler_PostShortenBatch_Call {
	return &MockRouterHandler_PostShortenBatch_Call{Call: _e.mock.On("PostShortenBatch", w, r)}
}

func (_c *MockRouterHandler_PostShortenBatch_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockRouterHandler_PostShortenBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRouterHandler_PostShortenBatch_Call) Return() *MockRouterHandler_PostShortenBatch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouterHandler_PostShortenBatch_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockRouterHandler_PostShortenBatch_Call {
	_c.Run(run)
	return _c
}
