// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepoChecker creates a new instance of MockRepoChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepoChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepoChecker {
	mock := &MockRepoChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepoChecker is an autogenerated mock type for the RepoChecker type
type MockRepoChecker struct {
	mock.Mock
}

type MockRepoChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepoChecker) EXPECT() *MockRepoChecker_Expecter {
	return &MockRepoChecker_Expecter{mock: &_m.Mock}
}

// PingContext provides a mock function for the type MockRepoChecker
func (_mock *MockRepoChecker) PingContext(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PingContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepoChecker_PingContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PingContext'
type MockRepoChecker_PingContext_Call struct {
	*mock.Call
}

// PingContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepoChecker_Expecter) PingContext(ctx interface{}) *MockRepoChecker_PingContext_Call {
	return &MockRepoChecker_PingContext_Call{Call: _e.mock.On("PingContext", ctx)}
}

func (_c *MockRepoChecker_PingContext_Call) Run(run func(ctx context.Context)) *MockRepoChecker_PingContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoChecker_PingContext_Call) Return(err error) *MockRepoChecker_PingContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepoChecker_PingContext_Call) RunAndReturn(run func(ctx context.Context) error) *MockRepoChecker_PingContext_Call {
	_c.Call.Return(run)
	return _c
}
