// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/eshadow1/shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockRepository
func (_mock *MockRepository) Close() {
	_mock.Called()
	return
}

// MockRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Close() *MockRepository_Close_Call {
	return &MockRepository_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockRepository_Close_Call) Run(run func()) *MockRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Close_Call) Return() *MockRepository_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepository_Close_Call) RunAndReturn(run func()) *MockRepository_Close_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRepository_Expecter) Get(ctx interface{}, key interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, key string)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(s string, err error) *MockRepository_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserURLs provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUserURLs(ctx context.Context) ([]model.UserURL, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserURLs")
	}

	var r0 []model.UserURL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.UserURL, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.UserURL); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserURL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserURLs'
type MockRepository_GetUserURLs_Call struct {
	*mock.Call
}

// GetUserURLs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetUserURLs(ctx interface{}) *MockRepository_GetUserURLs_Call {
	return &MockRepository_GetUserURLs_Call{Call: _e.mock.On("GetUserURLs", ctx)}
}

func (_c *MockRepository_GetUserURLs_Call) Run(run func(ctx context.Context)) *MockRepository_GetUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetUserURLs_Call) Return(userURLs []model.UserURL, err error) *MockRepository_GetUserURLs_Call {
	_c.Call.Return(userURLs, err)
	return _c
}

func (_c *MockRepository_GetUserURLs_Call) RunAndReturn(run func(ctx context.Context) ([]model.UserURL, error)) *MockRepository_GetUserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepository
func (_mock *MockRepository) Save(ctx context.Context, values []model.URLInfo) error {
	ret := _mock.Called(ctx, values)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.URLInfo) error); ok {
		r0 = returnFunc(ctx, values)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - values []model.URLInfo
func (_e *MockRepository_Expecter) Save(ctx interface{}, values interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save", ctx, values)}
}

func (_c *MockRepository_Save_Call) Run(run func(ctx context.Context, values []model.URLInfo)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.URLInfo
		if args[1] != nil {
			arg1 = args[1].([]model.URLInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(err error) *MockRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(ctx context.Context, values []model.URLInfo) error) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
